"""
Mini pretraining pipeline for a ~10GB Python subset of The Stack v2.
Run:
    python run_pipeline.py
Outputs parquet shards under ./output/final/
"""
import os, re
from datatrove.executor.local import LocalPipelineExecutor
from datatrove.pipeline.readers import ParquetReader
from datatrove.pipeline.writers import ParquetWriter, JsonlWriter
from datatrove.pipeline.base import PipelineStep
from datatrove.pipeline.dedup import (
    MinhashDedupSignature, MinhashDedupBuckets,
    MinhashDedupCluster, MinhashDedupFilter, MinhashConfig,
)
from datatrove.pipeline.filters import LambdaFilter
from datatrove.data import Document

# ---------------------------------------------------------------------------
# 1) 启发式过滤（StarCoder2 规则精简版）
# ---------------------------------------------------------------------------
AUTOGEN_MARKERS = re.compile(
    r"(DO NOT EDIT|AUTO-?GENERATED|@generated|Code generated by)",
    re.IGNORECASE,
)

def heuristic_ok(doc: Document) -> bool:
    text = doc.text
    if not text or len(text) < 50:
        return False
    lines = text.splitlines()
    if len(lines) < 3 or len(lines) > 100_000:
        return False
    max_line = max(len(l) for l in lines)
    avg_line = sum(len(l) for l in lines) / max(1, len(lines))
    if max_line > 1000 or avg_line > 100:
        return False
    # 字母比例
    letters = sum(c.isalpha() for c in text)
    if letters / max(1, len(text)) < 0.15:
        return False
    # autogen
    head = text[:2000]
    if AUTOGEN_MARKERS.search(head):
        return False
    # python 特有：至少得有一个 def/class/import
    if not re.search(r"^\s*(def |class |import |from )", text, re.MULTILINE):
        return False
    return True

# ---------------------------------------------------------------------------
# 2) PII 脱敏（只做最致命的几类；生产走 starpii）
# ---------------------------------------------------------------------------
PII_PATTERNS = [
    (re.compile(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}"), "<EMAIL>"),
    (re.compile(r"-----BEGIN (?:RSA |DSA |EC |OPENSSH )?PRIVATE KEY-----.*?-----END [A-Z ]*PRIVATE KEY-----", re.DOTALL), None),  # 整块私钥 → 丢整文件
    (re.compile(r"ghp_[A-Za-z0-9]{36}"), "<GH_TOKEN>"),
    (re.compile(r"AKIA[0-9A-Z]{16}"), "<AWS_KEY>"),
    (re.compile(r"AIza[0-9A-Za-z\-_]{35}"), "<GCP_KEY>"),
    (re.compile(r"sk_live_[0-9a-zA-Z]{24,}"), "<STRIPE_KEY>"),
]

class PIIScrubber(PipelineStep):
    name = "pii_scrubber"
    type = "filter"
    def run(self, data, rank=0, world_size=1):
        for doc in data:
            drop = False
            text = doc.text
            for pat, rep in PII_PATTERNS:
                if rep is None:
                    if pat.search(text):
                        drop = True; break
                else:
                    text = pat.sub(rep, text)
            if drop:
                continue
            doc.text = text
            yield doc

# ---------------------------------------------------------------------------
# 3) 评测集去污染（10-gram）
# ---------------------------------------------------------------------------
def load_benchmark_ngrams(n=10):
    """加载 HumanEval / MBPP prompts 的 n-gram 集合，实际用请替换数据源。"""
    from datasets import load_dataset
    grams = set()
    for name, col in [("openai_humaneval", "prompt"), ("mbpp", "text")]:
        ds = load_dataset(name, split="test")
        for ex in ds:
            toks = ex[col].split()
            for i in range(len(toks) - n + 1):
                grams.add(" ".join(toks[i:i+n]))
    return grams

BENCH_GRAMS = None
def decontam_ok(doc: Document) -> bool:
    global BENCH_GRAMS
    if BENCH_GRAMS is None:
        BENCH_GRAMS = load_benchmark_ngrams()
    toks = doc.text.split()
    n = 10
    hits = 0
    for i in range(0, len(toks) - n + 1, 5):   # stride 5 加速
        if " ".join(toks[i:i+n]) in BENCH_GRAMS:
            hits += 1
            if hits >= 2:
                return False
    return True

# ---------------------------------------------------------------------------
# 4) FIM 改写（50% 概率）
# ---------------------------------------------------------------------------
import numpy as np
class FIMTransform(PipelineStep):
    name = "fim"
    type = "transform"
    def __init__(self, fim_rate=0.5, psm_rate=0.5, seed=0):
        super().__init__()
        self.fim_rate, self.psm_rate = fim_rate, psm_rate
        self.rng = np.random.default_rng(seed)
    def run(self, data, rank=0, world_size=1):
        for doc in data:
            t = doc.text
            if len(t) >= 10 and self.rng.random() < self.fim_rate:
                i, j = sorted(self.rng.integers(0, len(t), 2).tolist())
                p, m, s = t[:i], t[i:j], t[j:]
                if self.rng.random() < self.psm_rate:
                    doc.text = f"<fim_prefix>{p}<fim_suffix>{s}<fim_middle>{m}"
                else:
                    doc.text = f"<fim_suffix>{s}<fim_prefix>{p}<fim_middle>{m}"
            yield doc

# ---------------------------------------------------------------------------
# 5) Pipeline 组装
# ---------------------------------------------------------------------------
ROOT   = "./work"
INPUT  = "hf://datasets/bigcode/the-stack-v2-dedup/data/Python/*.parquet"   # 示例
STAGE1 = f"{ROOT}/stage1_filtered"
STAGE2_SIG = f"{ROOT}/stage2_sig"
STAGE2_BKT = f"{ROOT}/stage2_bkt"
STAGE2_CLU = f"{ROOT}/stage2_clu"
STAGE2_OUT = f"{ROOT}/stage2_dedup"
FINAL      = f"{ROOT}/final"

minhash_cfg = MinhashConfig(
    num_buckets=14,            # bands
    hashes_per_bucket=8,       # rows; 14*8=112 (中等规模 demo)
    n_grams=5,
    use_64bit_hashes=True,
)

# Stage A: 读取 + 启发式 + PII + decontam → parquet
executor_A = LocalPipelineExecutor(
    pipeline=[
        ParquetReader(INPUT, text_key="content", glob_pattern="*.parquet"),
        LambdaFilter(filter_function=heuristic_ok),
        PIIScrubber(),
        LambdaFilter(filter_function=decontam_ok),
        ParquetWriter(STAGE1),
    ],
    tasks=32,
    workers=16,
    logging_dir=f"{ROOT}/logs/A",
)

# Stage B: MinHash 去重（三步：签名 / 分桶 / 聚类 / 过滤）
executor_B1 = LocalPipelineExecutor(
    pipeline=[
        ParquetReader(STAGE1),
        MinhashDedupSignature(output_folder=STAGE2_SIG, config=minhash_cfg),
    ],
    tasks=32, workers=16, logging_dir=f"{ROOT}/logs/B1",
)
executor_B2 = LocalPipelineExecutor(
    pipeline=[
        MinhashDedupBuckets(input_folder=STAGE2_SIG,
                            output_folder=STAGE2_BKT,
                            config=minhash_cfg),
    ],
    tasks=minhash_cfg.num_buckets, workers=8,
    logging_dir=f"{ROOT}/logs/B2",
    depends=executor_B1,
)
executor_B3 = LocalPipelineExecutor(
    pipeline=[
        MinhashDedupCluster(input_folder=STAGE2_BKT,
                            output_folder=STAGE2_CLU,
                            config=minhash_cfg),
    ],
    tasks=1, workers=1,
    logging_dir=f"{ROOT}/logs/B3",
    depends=executor_B2,
)
executor_B4 = LocalPipelineExecutor(
    pipeline=[
        ParquetReader(STAGE1),
        MinhashDedupFilter(input_folder=STAGE2_CLU),
        ParquetWriter(STAGE2_OUT),
    ],
    tasks=32, workers=16,
    logging_dir=f"{ROOT}/logs/B4",
    depends=executor_B3,
)

# Stage C: FIM + 最终写出
executor_C = LocalPipelineExecutor(
    pipeline=[
        ParquetReader(STAGE2_OUT),
        FIMTransform(fim_rate=0.5, psm_rate=0.5, seed=42),
        ParquetWriter(FINAL),
    ],
    tasks=32, workers=16,
    logging_dir=f"{ROOT}/logs/C",
    depends=executor_B4,
)

if __name__ == "__main__":
    executor_C.run()
